//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, your school {0} has been created {1} Please download the user manual from the menu &apos;About&apos;.
        /// </summary>
        public static string AddSchool_Executed_Welcome__your_school__0__has_been_created__1__Please_download_the_user_manual_from_the_menu__About_ {
            get {
                return ResourceManager.GetString("AddSchool_Executed_Welcome__your_school__0__has_been_created__1__Please_download_" +
                        "the_user_manual_from_the_menu__About_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        public static string Afternoon {
            get {
                return ResourceManager.GetString("Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi Weekly.
        /// </summary>
        public static string Bi_Weekly {
            get {
                return ResourceManager.GetString("Bi_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BiWklySalary.
        /// </summary>
        public static string BiWklySalary {
            get {
                return ResourceManager.GetString("BiWklySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompuServe&apos;s Graphics Interchange Format.
        /// </summary>
        public static string CompuServe_s_Graphics_Interchange_Format {
            get {
                return ResourceManager.GetString("CompuServe_s_Graphics_Interchange_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Evening {
            get {
                return ResourceManager.GetString("Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Shirley&quot;,&quot;Rose&quot;,&quot;Sean&quot;,&quot;Jeremy&quot;,&quot;Donald&quot;,&quot;Douglas&quot;,&quot;Nancy&quot;,&quot;Heather&quot;,&quot;Debra&quot;,&quot;Mildred&quot;,&quot;Craig&quot;,&quot;Ann&quot;,&quot;Betty&quot;,&quot;Billy&quot;,&quot;Kathleen&quot;,&quot;Bonnie&quot;,&quot;Emily&quot;,&quot;Debra&quot;,&quot;Jessica&quot;,&quot;Heather&quot;,&quot;Marilyn&quot;,&quot;Wanda&quot;,&quot;Tina&quot;,&quot;Eugene&quot;,&quot;Brandon&quot;,&quot;Heather&quot;,&quot;Phyllis&quot;,&quot;Sarah&quot;,&quot;Norma&quot;,&quot;Dorothy&quot;,&quot;Jonathan&quot;,&quot;Harold&quot;,&quot;Jennifer&quot;,&quot;David&quot;,&quot;Ernest&quot;,&quot;Billy&quot;,&quot;Julia&quot;,&quot;Diane&quot;,&quot;Martin&quot;,&quot;Bonnie&quot;,&quot;Judith&quot;,&quot;Ernest&quot;,&quot;Charles&quot;,&quot;Jonathan&quot;,&quot;Denise&quot;,&quot;Howard&quot;,&quot;Bruce&quot;,&quot;Teresa&quot;,&quot;Paula&quot;,&quot;David&quot;,&quot;Stephen&quot;,&quot;Howard&quot;,&quot;Tina&quot;,&quot;Margaret&quot;,....
        /// </summary>
        public static string first_names {
            get {
                return ResourceManager.GetString("first_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Yearly.
        /// </summary>
        public static string Half_Yearly {
            get {
                return ResourceManager.GetString("Half_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HalfYearly.
        /// </summary>
        public static string HalfYearly {
            get {
                return ResourceManager.GetString("HalfYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint Photographic Experts Group.
        /// </summary>
        public static string Joint_Photographic_Experts_Group {
            get {
                return ResourceManager.GetString("Joint_Photographic_Experts_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Fernandez&quot;,&quot;Fernandez&quot;,&quot;Castillo&quot;,&quot;Frazier&quot;,&quot;Willis&quot;,&quot;Stone&quot;,&quot;Spencer&quot;,&quot;Castillo&quot;,&quot;Peters&quot;,&quot;White&quot;,&quot;Edwards&quot;,&quot;Edwards&quot;,&quot;Lopez&quot;,&quot;Fuller&quot;,&quot;Pierce&quot;,&quot;Richardson&quot;,&quot;Rose&quot;,&quot;Ramos&quot;,&quot;Roberts&quot;,&quot;Green&quot;,&quot;Stevens&quot;,&quot;Morris&quot;,&quot;Brooks&quot;,&quot;Warren&quot;,&quot;Allen&quot;,&quot;Sullivan&quot;,&quot;Mills&quot;,&quot;Gray&quot;,&quot;Wood&quot;,&quot;Walker&quot;,&quot;Coleman&quot;,&quot;Harvey&quot;,&quot;Gordon&quot;,&quot;Morrison&quot;,&quot;Ruiz&quot;,&quot;Morris&quot;,&quot;Dixon&quot;,&quot;Gonzales&quot;,&quot;Ward&quot;,&quot;Thomas&quot;,&quot;Bennett&quot;,&quot;Rivera&quot;,&quot;Gonzalez&quot;,&quot;Bowman&quot;,&quot;Myers&quot;,&quot;Burns&quot;,&quot;Patterson&quot;,&quot;Lopez&quot;,&quot;Ramos&quot;,&quot;Riley&quot;,&quot;Stevens&quot;,&quot;Holmes&quot;,&quot;Cook&quot;,&quot....
        /// </summary>
        public static string last_names {
            get {
                return ResourceManager.GetString("last_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Windows Bitmap formatted image.
        /// </summary>
        public static string Microsoft_Windows_Bitmap_formatted_image {
            get {
                return ResourceManager.GetString("Microsoft_Windows_Bitmap_formatted_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        public static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphic.
        /// </summary>
        public static string Portable_Network_Graphic {
            get {
                return ResourceManager.GetString("Portable_Network_Graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        public static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Image File Format.
        /// </summary>
        public static string Tagged_Image_File_Format {
            get {
                return ResourceManager.GetString("Tagged_Image_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WklySalary.
        /// </summary>
        public static string WklySalary {
            get {
                return ResourceManager.GetString("WklySalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
